apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-docker
  labels:
    pv: reg
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /registry-volume
