apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: docker-registry
  name: cert-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
  selector:
    matchLabels:
      pv: registry-cert
