apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-cert
  labels:
    pv: registry-cert
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /opt/certs
